name: Checks

on: workflow_call
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/nodejs@v2
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run lint
