name: Checks

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout repository'
        uses: actions/checkout@v4
      - name: 'setup node'
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn lint
